name: twim
version: 0.1.0.0
homepage: https://github.com/aiya000/twim
author: aiya000
copyright: 2021- aiya000

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -fprint-explicit-kinds
  - -fprint-potential-instances

default-extensions:
  - BangPatterns
  - BinaryLiterals
  - BlockArguments
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DerivingVia
  - DoAndIfThenElse
  - DuplicateRecordFields
  - EmptyDataDecls
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - PartialTypeSignatures
  - PatternGuards
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeSynonymInstances
  - ViewPatterns

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - directory
  - easy-file
  - extra
  - here
  - optparse-applicative
  - safe
  - safe-exceptions

library:
  source-dirs: src

executables:
  twim:
    source-dirs: app
    main: Main.hs
    dependencies:
      - twim

tests:
  tasty:
    main: Main.hs
    source-dirs:
      - test/tasty
      - src
    dependencies:
      - smallcheck
      - tasty
      - tasty-discover
      - tasty-hunit
      - tasty-smallcheck
